=== Siddharthsas07/Web-Programming-Language/Assignments/sas151830_Assignment4/XML_Books.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="amazon_books">
	<xsd:complexType>
		<xsd:sequence>	
			<xsd:element ref="book_Info"  maxOccurs="unbounded"/>
		</xsd:sequence>				
	</xsd:complexType>
</xsd:element>

<xsd:element name="book_Info">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="title"/>
			<xsd:element ref="isbn"/>
			<xsd:element ref="price"/>
			<xsd:element ref="publication_Date"/>
			<xsd:element ref="circulation_Time"/>
			<xsd:element ref="author_Info"  maxOccurs="unbounded"/>
			<xsd:element ref="publisher_Info"/>
		</xsd:sequence>				
	</xsd:complexType>
</xsd:element>


<xsd:element name="author_Info" >
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="author_Name"/>
			<xsd:element ref="dob"/>
			<xsd:element ref="education"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="author_Name" >
	<xsd:complexType>
		<xsd:all>
			<xsd:element ref="last_Name"/>
			<xsd:element ref="middle_Initial"/>
			<xsd:element ref="first_Name"/>
		</xsd:all>	
	</xsd:complexType>
</xsd:element>


<xsd:element name="publisher_Info" >
	<xsd:complexType>
		<xsd:all>
			<xsd:element ref="publisher_Name"/>
			<xsd:element ref="publisher_Address"/>
		</xsd:all>	
	</xsd:complexType>
</xsd:element>

<xsd:element name="publisher_Address" >
	<xsd:complexType>
				<xsd:sequence>
					<xsd:element ref="street_Name"/>
					<xsd:element ref="suite_Number" minOccurs="0" maxOccurs="1"/>
					<xsd:element ref="city"/>
					<xsd:element ref="zip"/>
					<xsd:element ref="country"/>
				</xsd:sequence>	
	</xsd:complexType>
</xsd:element>






	<xsd:element name="last_Name" >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][a-z]*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>	 
	
	<xsd:element name="middle_Initial"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z]\."/>
			</xsd:restriction>
		 </xsd:simpleType>	
	</xsd:element>
	
	<xsd:element name="first_Name"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][a-z]*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>



	<xsd:element name="dob" >
		<xsd:simpleType>
			<xsd:restriction base="xsd:date">
				  <xsd:minInclusive value="1900-01-01"/>
   				  <xsd:maxInclusive value="2015-10-31"/>
  			</xsd:restriction>
 		</xsd:simpleType>
 	</xsd:element>	

 	<xsd:element name="education"  >
 		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="BA"/>
			    <xsd:enumeration value="BS"/>
			    <xsd:enumeration value="MS"/>
			    <xsd:enumeration value="MBA"/>
    			<xsd:enumeration value="PHD"/>
			</xsd:restriction>
		 </xsd:simpleType>
 	</xsd:element>	


	<xsd:element name="publisher_Name"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][a-zA-Z]*(\s[A-Z][a-zA-Z]*)*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>

	<xsd:element name="street_Name"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9][0-9]*\s[A-Z][a-z]*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>

	<xsd:element name="suite_Number"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:integer">
				<xsd:pattern value="[0-9]*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>

	<xsd:element name="city"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][a-z]*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>

	<xsd:element name="zip"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:integer">
				<xsd:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
				 <xsd:minInclusive value="11111"/>
   				  <xsd:maxInclusive value="99999"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>

	<xsd:element name="country"  >
		 <xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z]*"/>
			</xsd:restriction>
		 </xsd:simpleType>
	</xsd:element>


	<xsd:element name="title"  >
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][a-zA-Z]*(\s[A-Z][a-zA-Z]*)*"/>
				<xsd:maxLength value="100"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<xsd:element name="isbn"  >
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Za-z0-9]{3}\-[A-Za-z0-9]{3}\-[A-Za-z0-9]{4}"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>


	<xsd:element name="price">
		<xsd:complexType>
			    <xsd:simpleContent>
					<xsd:extension base="xsd:decimal">
						<xsd:attribute name="currency" type="xsd:string" use="required"/>		
					</xsd:extension>	
				</xsd:simpleContent>	
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="publication_Date" type="xsd:date"/>

	<xsd:element name="circulation_Time" type="xsd:duration"/>


</xsd:schema>

=== Siddharthsas07/Web-Programming-Language/Assignments/sas151830_Assignment4/XML_Books.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<amazon_books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_books.xsd">
	<book_Info>
		<title>Digital Fortress</title>
		<isbn>439-x34-B9r2</isbn>
		<price currency="USD">35.39</price>
		<publication_Date>2002-01-18</publication_Date>
		<circulation_Time>PT130S</circulation_Time>
		<author_Info>
			<author_Name>
				<last_Name>Brown</last_Name>
				<middle_Initial>C.</middle_Initial>
				<first_Name>Dan</first_Name>
			</author_Name>

			<dob>1991-03-23</dob>
			<education>BA</education>
		</author_Info>


		<publisher_Info>
			<publisher_Name>Morgan Kaufmann</publisher_Name>
			<publisher_Address>
				<street_Name>175 Fifth Avenue</street_Name>
				<suite_Number>901</suite_Number>
				<city>New York</city>
				<zip>10010</zip>
				<country>USA</country>
			</publisher_Address>
		</publisher_Info>
	</book_Info>

	<book_Info>
		<title>Bleachers</title>
		<isbn>034-553-2031</isbn>
		<price currency="USD">8.55</price>
		<publication_Date>2003-09-09</publication_Date>
		<circulation_Time>PT2M10S</circulation_Time>
		<author_Info>
			<author_Name>
				<last_Name>Grisham</last_Name>
				<middle_Initial>D.</middle_Initial>
				<first_Name>John</first_Name>
			</author_Name>
			<dob>1967-11-15</dob>
			<education>MS</education>
		</author_Info>
		<publisher_Info>
			<publisher_Name>Doubleday</publisher_Name>
			<publisher_Address>
				<street_Name>1745 Broadway</street_Name>
				<suite_Number></suite_Number>
				<city>New York</city>
				<zip>10019</zip>
				<country>USA</country>
			</publisher_Address>
		</publisher_Info>
	</book_Info>

	<book_Info>
		<title>INTRODUCTION TO ALGORITHMS</title>
		<isbn>026-203-2937</isbn>
		<price currency="USD">35.24</price>
		<publication_Date>2012-03-12</publication_Date>
		<circulation_Time>P1DT2S</circulation_Time>
		<author_Info>
			<author_Name>
				<last_Name>Cormen</last_Name>
				<middle_Initial>H.</middle_Initial>
				<first_Name>Thomas</first_Name>
			</author_Name>
			<dob>1956-04-22</dob>
			<education>PHD</education>
		</author_Info>
		<publisher_Info>
			<publisher_Name>MIT Press</publisher_Name>
			<publisher_Address>
				<street_Name>1 Rogers St</street_Name>
				<suite_Number>901</suite_Number>
				<city>Cambridge</city>
				<zip>02142</zip>
				<country>USA</country>
			</publisher_Address>
		</publisher_Info>
	</book_Info>

	<book_Info>
		<title>DSCJP Sun Certified Programmer for Java</title>
		<isbn>007-159-1060</isbn>
		<price currency="USD">29.59</price>
		<publication_Date>2002-04-29</publication_Date>
		<circulation_Time>PT130S</circulation_Time>
		<author_Info>
			<author_Name>
				<last_Name>Sierra</last_Name>
				<middle_Initial>J.</middle_Initial>
				<first_Name>Kathy</first_Name>
			</author_Name>
			<dob>1976-11-25</dob>
			<education>MBA</education>
		</author_Info>
		<publisher_Info>
			<publisher_Name>Pearson Education</publisher_Name>
			<publisher_Address>
				<street_Name>6025 Commerce Dr</street_Name>
				<suite_Number>2215</suite_Number>
				<city>Irving</city>
				<zip>75063</zip>
				<country>USA</country>
			</publisher_Address>
		</publisher_Info>
	</book_Info>

	<book_Info>
		<title>Forest Gump</title>
		<isbn>439-x34-E9r2</isbn>
		<price currency="USD">35.39</price>
		<publication_Date>2002-01-18</publication_Date>
		<circulation_Time>PT130S</circulation_Time>
		<author_Info>
			<author_Name>
				<last_Name>Robert</last_Name>
				<middle_Initial>C.</middle_Initial>
				<first_Name>Brown</first_Name>
			</author_Name>
			<dob>1991-03-23</dob>
			<education>BA</education>
		</author_Info>
		<publisher_Info>
			<publisher_Name>Morgan Kaufmann</publisher_Name>
			<publisher_Address>
				<street_Name>1920 Fifth Capitol</street_Name>
				<suite_Number>901</suite_Number>
				<city>New York</city>
				<zip>10010</zip>
				<country>USA</country>
			</publisher_Address>
		</publisher_Info>
	</book_Info>

</amazon_books>
